### PR TITLE
Use custom reflection utils rather than depend on viewpump internals

### LINKED ISSUE #19: upgrade Calligraphy for viewpump:2.0.0
please upgrade Calligraphy for match with
io.github.inflationx:viewpump:2.0.0

### LINKED ISSUE #22: crash on Android Q
I test the library targeting Android Q
I have a crash. Seems related to reflection 
`     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.reflect.Field.get(java.lang.Object)' on a null object reference
        at io.github.inflationx.viewpump.ReflectionUtils.getValue(ReflectionUtils.java:25)
        at io.github.inflationx.viewpump.ViewPumpLayoutInflater.createCustomViewInternal(ViewPumpLayoutInflater.java:196)
        at io.github.inflationx.viewpump.ViewPumpLayoutInflater.access$000(ViewPumpLayoutInflater.java:14)
        at io.github.inflationx.viewpump.ViewPumpLayoutInflater$PrivateWrapperFactory2ViewCreator.onCreateView(ViewPumpLayoutInflater.java:405)
        at io.github.inflationx.viewpump.FallbackViewCreationInterceptor.intercept(FallbackViewCreationInterceptor.java:11)
        at io.github.inflationx.viewpump.InterceptorChain.proceed(InterceptorChain.java:37)
        at io.github.inflationx.calligraphy3.CalligraphyInterceptor.intercept(CalligraphyInterceptor.java:18)
        at io.github.inflationx.viewpump.InterceptorChain.proceed(InterceptorChain.java:37)
        at io.github.inflationx.viewpump.ViewPump.inflate(ViewPump.java:49)
        at io.github.inflationx.viewpump.ViewPumpLayoutInflater$PrivateWrapperFactory2.onCreateView(ViewPumpLayoutInflater.java:385)
        at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:235)`

### PR DESCRIPTION
**Pull request by ZacSweers**
Resolves #22
Resolves #19

### CODE REVIEW

**Review by jbarr21 — APPROVED** [review]

**Comment by rraallvv** [comment]
So, can Calligraphy be used without ViewPump? How?

**Comment by ZacSweers** [comment]
@rraallvv not calligraphy 3. Why?

**Comment by chrisjenx** [comment]
@rraallvv Calligraphy 3, uses ViewPump as the underlying inflation mechanism, Calligraphy 2 was split out to ViewPump and Calligraphy 3, it's about the same amount of code just more intercept-able.

**Comment by rraallvv** [comment]
@ZacSweers, maybe it's just me after a long day of trying all sorts of workarounds to load customs fonts on Lollipop, but it seems that less dependencies would make the solution less prone to failures an simple, at least when it comes to integrating the library in my app.

**Comment by rraallvv** [comment]
@chrisjenx thanks, I'll give it a try.

**Pull request merged**
